import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Button, Center } from "@mantine/core";
import { APP_NAME } from "@/constants/appName";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>{APP_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Center mih="100vh">This is the Homies app!</Center>
      </main>
    </>
  );
}
